// ==UserScript==
// @name          2021-12月更新 百度多栏BaiduXs 百度Xs-简洁 多栏 卡片
// @namespace     http://userstyles.org
// @description	  BaiduXs - 多栏卡片样式，自动调整 1~4 列。清爽简洁，无广告。
// @author        moonflame
// @homepage      https://userstyles.org/styles/189519
// @include       http://baidu.com*
// @include       http://www.baidu.com*
// @include       https://www.baidu.com*
// @include       https://baidu.com*
// @run-at        document-start
// @version       0.20211214035329
// ==/UserScript==
(function() {var css = [
	"body {",
	"    overflow-x: hidden;",
	"    min-width: 600px;",
	"}",
	"",
	"/*关键词高亮*/",
	"em,",
	"font[color=\"#CC0000\"] {",
	"    color: #C00 !important;",
	"    text-decoration: none !important;",
	"}",
	"",
	".wrapper_l .s_form {",
	"    width: 900px;",
	"    margin: 0 auto;",
	"    transform: translatex(-40px);",
	"}",
	".s_tab,",
	".nums,",
	".search_tool_conter,",
	"#rs,",
	".to_tieba,",
	".to_zhidao_bottom {",
	"    margin: 0 auto !important;",
	"}",
	".headBlock {",
	"    margin-left: 0;",
	"}",
	".headBlock > div {",
	"    margin: auto;",
	"}",
	".head_nums_cont_inner > div {",
	"    width: 600px;",
	"}",
	"#page,",
	"#s_tab {",
	"    padding-left: 0px !important;",
	"    text-align: center !important;",
	"}",
	".wrapper_new .container_new~#page {",
	"    margin-top: 0;",
	"}",
	"#container {",
	"    width: 100%;",
	"}",
	"#content_right {",
	"    display: none;",
	"}",
	"#content_left {",
	"    padding: 0;",
	"    width: 98%;",
	"    padding-left: 1%;",
	"    display: block;",
	"    counter-reset: results;",
	"    column-gap: 0;",
	"    -moz-column-gap: 0;",
	"    -webkit-column-gap: 0;",
	"}",
	".rrecom-container,",
	".xpath-log:not(.c-container) {",
	"    transform: scale(0);",
	"}",
	"/* 方向自定义 start */",
	"/* 纵向 vertical */",
	"@media (min-width: 1050px) and (max-width: 1500px) {",
	"    .wrapper_new #content_left {",
	"        column-count: 2;",
	"        -moz-column-count: 2;",
	"        -webkit-column-count: 2;",
	"    }",
	"}",
	"@media (min-width: 1501px) and (max-width: 2200px) {",
	"    .wrapper_new #content_left {",
	"        column-count: 3;",
	"        -moz-column-count: 3;",
	"        -webkit-column-count: 3;",
	"    }",
	"}",
	"@media (min-width: 2201px) {",
	"    .wrapper_new #content_left {",
	"        column-count: 4;",
	"        -moz-column-count: 4;",
	"        -webkit-column-count: 4;",
	"    }",
	"}",
	"#content_left > div[class*=\"c-container\"], #content_left > div[class*=\"c-group-wrapper\"] {",
	"    display: inline-block;",
	"    width: 92%;",
	"    padding: 18px 15px;",
	"    margin: 1em;",
	"    word-break: normal;",
	"    word-wrap: normal;",
	"    position: relative;",
	"    z-index: 1;",
	"    box-shadow: inset 0px -3px 0px 0 rgba(0, 0, 0, 0.16), 0px 0px 1px 1px rgba(0, 0, 0, 0.12);",
	"    border-radius: 6px;",
	"/*     background-color: white; */",
	"    overflow: hidden;",
	"}",
	"/* 方向自定义 end */",
	"/* 修复新闻热点等特殊卡片显示 */",
	"/* #content_left > div:not([class*=\"c-container\"]) {",
	"    position: absolute;",
	"    margin-top: -1em;",
	"    margin-left: 1em;",
	"}*/",
	"",
	"/* 搜索结果卡片编号 */",
	"#content_left > div[class*=\"c-container\"]:before {",
	"    counter-increment: results;",
	"    content: counter(results);",
	"    z-index: -10;",
	"    color: #eee;",
	"    font-size: 4.5em;",
	"    position: absolute;",
	"    text-align: right;",
	"    width: 96%;",
	"    line-height: 1em;",
	"    top: 2px;",
	"}",
	"#content_left > div[class*=\"c-container\"] .sitelink {",
	"    word-wrap: break-word;",
	"}",
	".c-border {",
	"    border: 0;",
	"    box-shadow: none;",
	"}",
	".to_tieba {",
	"    display: none;",
	"}",
	".hint_common_restop {",
	"    display: none;",
	"}",
	"#rs {",
	"    width: 100%;",
	"    text-align: center;",
	"    padding: 0;",
	"    margin: 0;",
	"    margin-top: 10px;",
	"}",
	"#rs .tt,",
	"#rs table,",
	"#rs tr,",
	"#rs td,",
	"#rs th {",
	"    display: inline;",
	"    padding: 0 5px;",
	"}",
	"#page {",
	"    margin: 0 !important;",
	"    text-align: center !important;",
	"    padding: 0 !important;",
	"}",
	"#page .fk {",
	"    display: none !important;",
	"}",
	"#page > a,",
	"#page > strong {",
	"    height: auto !important;",
	"}",
	"#foot {",
	"    /*   margin-top: 35px !important; */",
	"    text-align: center !important;",
	"}",
	"#foot #help {",
	"    float: none !important;",
	"    padding: 0 !important;",
	"}",
	"",
	"",
	"div#head {",
	"    min-height: 0px!important;",
	"    -webkit-backdrop-filter: blur(20px);",
	"    /*     backdrop-filter: blur(20px); */",
	"    /*     background-color: rgba(255, 255, 255, 0.8); */",
	"}",
	"div#head_wrapper {",
	"    min-height: 0px!important",
	"}",
	"div#bottom_container {",
	"    display: none!important",
	"}",
	"a.s-treasure {",
	"    display: none!important",
	"}",
	"a.mnav,",
	"a.s-skin,",
	"a.s-msg,",
	"span.user-name,",
	"span.setting-text {",
	"    text-decoration: none!important",
	"}",
	"a:hover {",
	"    text-decoration: none!important",
	"}",
	"* {",
	"    text-decoration: none!important",
	"}",
	".t a:hover > a {",
	"    text-shadow: 1px 1px 20px #aaa;",
	"}",
	".t a {",
	"    position: relative;",
	"}",
	"/* 指向关键词时的下划线 */",
	".t a:before {",
	"    content: \"\";",
	"    position: absolute;",
	"    left: 0;",
	"    bottom: -2px;",
	"    width: 102%;",
	"    height: 2px;",
	"    transition: all .15s;",
	"}",
	".t a:hover:before {",
	"    background-color: #3385ff;",
	"}",
	"/* 2020-09-08 添加宽度和缩进 */",
	"#container.sam_newgrid #content_left {",
	"    width: 98%",
	"}",
	"#container.sam_newgrid {",
	"    margin-left: 1%;",
	"}",
	"/* 2020-09-17 调整搜索页大多数元素的右间距 */",
	"/* .new-pmd .c-span2,",
	".new-pmd .c-span3,",
	".new-pmd .c-span4,",
	".new-pmd .c-span5,",
	".new-pmd .c-span6,",
	".new-pmd .c-span7,",
	".new-pmd .c-span8,",
	".new-pmd .c-span9,",
	".new-pmd .c-span10,",
	".new-pmd .c-span11,",
	".new-pmd .c-span12 {",
	"    margin-right: 4px;",
	"} */",
	"/* 缩小条目纵向间距 */",
	"#container.sam_newgrid #content_left .result-op,",
	"#container.sam_newgrid #content_left .result {",
	"    margin-top: 10px;",
	"    margin-bottom: 2px;",
	"}",
	"/* 底部相关搜索样式 */",
	"#rs .new-pmd .tt {",
	"    vertical-align: middle;",
	"}",
	"#foot .foot-inner #help .activity {",
	"    display: none;",
	"}",
	"/* 购物卡片去背景 */",
	"[data-pmd] .c-container {",
	"    background: none;",
	"}",
	"/* 去除“其他人还在搜” */",
	"#container .result-op[tpl=recommend_list] {",
	"    display: none;",
	"}",
	"/* 超宽屏宽度设置 */",
	"#wrapper_wrapper {",
	"    margin-left: 0;",
	"}",
	"#container, #container.sam_newgrid {",
	"    width: 100%;",
	"    margin-left: 0;",
	"    padding-left: 1%;",
	"}",
	"#head .head_wrapper {",
	"    width: 100%;",
	"/*     transform: none; */",
	"/* transform 引起顶部栏变化，需观察超宽屏情况下是否需要去除 transform */",
	"}",
	"/* 超宽屏的顶部搜索种类栏样式 */",
	".wrapper_new #s_tab.s_tab .s_tab_inner {",
	"    padding-left: 0;",
	"}",
	"/* 底部“相关搜索” */",
	"/* #rs .new-inc-rs-item {",
	"    width: auto;",
	"    margin-right: 10px;",
	"} */",
	"/* 背景颜色 start */",
	"/* 白色背景 white */",
	"/* 背景颜色 end */",
	"",
	"/* 是否隐藏底部“相关搜索” start */",
	"/* 不隐藏 */",
	"/* 是否隐藏底部“相关搜索” end */"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
